---
- name: Destroy container instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove test containers
      containers.podman.podman_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ groups['all'] }}"
      failed_when: false

    - name: Remove container network
      containers.podman.podman_network:
        name: molecule-pihole-test
        state: absent
      failed_when: false
