---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

ansible:
  cfg:
    defaults:
      vvv: True
      deprecation_warnings: false
      roles_path: "$MOLECULE_SCENARIO_DIRECTORY/../../../"
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory.yml

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
