# This is a basic workflow to help you get started with Actions

name: Verify on Ubuntu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:    
  test-role:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install curl ansible
      - name: Check
        run: |
          ls
      - name: Run the role
        run: |
          ansible -i localhost --module-name include_role --args name=pihole
    
      
